name: emsforai
channels:
  - conda-forge
dependencies:
  - python=3.11
  - fastapi>=0.110
  - uvicorn>=0.23
  - sqlalchemy>=1.4
  - pydantic
  - numpy
  - scipy
  - aiofiles
  - python-dotenv
  - alembic
  - pip
  - statsmodels
  - pip:
      - fastapi-cli
      - psycopg2-binary
      - xgboost
      - scikit-learn
      - pandas
      - torch
      - tqdm
      - matplotlib
